---
name: Ping!

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: |-
          do_that | echo "pong!"
          echo "exit status: $?"
